#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "ssh://git@github.com/bdelacretaz/helixing.git"

strains:
  - name: default
    code: ssh://git@github.com/bdelacretaz/helixing.git#master
    content: ssh://git@github.com/bdelacretaz/helixing.git#master
    static: ssh://git@github.com/bdelacretaz/helixing.git/htdocs#master
    package: bdelacre/68afa88c709108554d91071b3c9b78f54dc0c66c
  - name: dev
    url: https://bertrand.helix-demo.xyz/DEV/
    code: ssh://git@github.com/bdelacretaz/helixing.git#dev
    content: ssh://git@github.com/bdelacretaz/helixing.git#master
    static: ssh://git@github.com/bdelacretaz/helixing.git/htdocs#master
    package: bdelacre/9cb88d63ec4a51b00f1a774523fb6231ff875c9e
